export default {
  index: 'Overview',
  framework: 'Framework',
  inventory: 'Inventory',
  banking: 'Banking',
  bossmenu: 'Boss Menu',
  clothing: 'Clothing',
  dialogue: 'Dialogue',
  dispatch: 'Dispatch',
  doorlock: 'Doorlock',
  fuel: 'Fuel',
  helptext: 'HelpText',
  housing: 'Housing',
  input: 'Input',
  locales: 'Locales',
  menu: 'Menu',
  notify: 'Notify',
  phone: 'Phone',
  progressbar: 'Progress Bar',
  shops: 'Shops',
  skills: 'Skills',
  target: 'Target',
  vehiclekey: 'Vehicle Key',
  version: 'Version',
  weather: 'Weather',
  zones: 'Zones'
}
